-- ==============================================================================
-- SQL/FUNCIONES.SQL - FUNCIONES PROCEDIMENTALES ALMACENADAS
-- ==============================================================================
-- Según el documento P2 (Secciones 3, 5.1 y regla A5):
--
-- FUNCIÓN A5: Salones disponibles para cotización y reserva
--
-- Nombre sugerido: fn_salones_disponibles(p_inicio TIMESTAMP, p_fin TIMESTAMP, p_aforo INT)
-- Retorno sugerido: TABLE (
--     salon_id INT,
--     nombre VARCHAR,
--     tamano VARCHAR,
--     capacidad INT,
--     precio_hora NUMERIC,
--     costo_estimado NUMERIC
-- )
--
-- Requerimientos de la lógica de negocio:
-- 1. Filtrar únicamente salones habilitados (disponible = TRUE).
-- 2. Filtrar salones cuya capacidad máxima sea mayor o igual al aforo solicitado (capacidad >= p_aforo).
-- 3. Excluir salones que tengan eventos no cancelados que se crucen con el rango pedido,
--    TENIENDO EN CUENTA LA HORA DE MONTAJE Y ASEO ENTRE EVENTOS:
--    - Ningún evento no cancelado en el mismo salón debe solaparse considerando que cada evento
--      ocupa el salón desde su inicio hasta (fin + 1 hora de montaje/aseo).
-- 4. Calcular el costo_estimado del alquiler para ese horario:
--    - Duración en horas: CEIL(EXTRACT(EPOCH FROM (p_fin - p_inicio)) / 3600.0)
--    - Costo estimado = duración_horas * precio_hora del salón.
-- 5. ORDENAMIENTO OBLIGATORIO:
--    - Del salón más pequeño que sirva al más grande (ORDER BY capacidad ASC).
--    - Esto garantiza ofrecer primero la opción más ajustada al aforo.
-- ==============================================================================
